/**
 * Clase socios para trabajar con los botones del menú y el fichero datos.txt
 * @author Manel Márquez
 * @version 6/02/2017
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;


public class Socis extends javax.swing.JFrame {

    ArrayList<String> arraySocios = new ArrayList<>();
    int endevant = 0;

    /**
     * Creates new form Socies
     */
    public Socis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        debe = new javax.swing.JTextField();
        alquilerUltimo = new javax.swing.JFormattedTextField();
        postal = new javax.swing.JTextField();
        clientNum = new javax.swing.JTextField();
        telf1 = new javax.swing.JTextField();
        telf2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        antiguedad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        alquiler = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        credito = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nacimiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        poblacion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        gastado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        bonos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        provincia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        nif = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana introducir datos de los clientes del videoclub ");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1500, 700));
        setMinimumSize(new java.awt.Dimension(1500, 700));
        setPreferredSize(new java.awt.Dimension(1500, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Antigüedad:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 90, 70, 14);

        jLabel2.setText("Debe:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 150, 40, 14);

        jLabel3.setText("Último alquiler:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 200, 90, 14);

        jLabel4.setText("C.Postal:");
        jLabel4.setAlignmentX(1.0F);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 330, 60, 14);

        jLabel5.setText("Cliente nº:");
        jLabel5.setAlignmentX(1.0F);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 80, 60, 14);

        jLabel6.setText("Teléfonos:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 380, 60, 14);
        getContentPane().add(debe);
        debe.setBounds(520, 140, 50, 30);
        getContentPane().add(alquilerUltimo);
        alquilerUltimo.setBounds(520, 190, 110, 30);

        postal.setAlignmentX(1.0F);
        getContentPane().add(postal);
        postal.setBounds(90, 320, 70, 30);

        clientNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clientNum.setAlignmentX(1.0F);
        getContentPane().add(clientNum);
        clientNum.setBounds(90, 70, 40, 30);
        getContentPane().add(telf1);
        telf1.setBounds(90, 370, 90, 30);
        getContentPane().add(telf2);
        telf2.setBounds(190, 370, 110, 30);

        jLabel7.setText("Dirección:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 420, 60, 14);
        getContentPane().add(direccion);
        direccion.setBounds(90, 410, 340, 40);
        getContentPane().add(antiguedad);
        antiguedad.setBounds(520, 80, 210, 40);

        jLabel8.setText("Nº alquileres:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 250, 80, 14);
        getContentPane().add(alquiler);
        alquiler.setBounds(520, 240, 50, 30);

        jLabel9.setText("Credito:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 290, 60, 14);
        getContentPane().add(credito);
        credito.setBounds(520, 280, 60, 30);

        jLabel10.setText("F.nacimiento:");
        jLabel10.setAlignmentX(1.0F);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 250, 80, 14);

        nacimiento.setAlignmentX(1.0F);
        getContentPane().add(nacimiento);
        nacimiento.setBounds(90, 240, 190, 30);

        jLabel11.setText("Población:");
        jLabel11.setAlignmentX(1.0F);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 290, 60, 14);

        poblacion.setAlignmentX(1.0F);
        getContentPane().add(poblacion);
        poblacion.setBounds(90, 280, 190, 30);

        jLabel13.setText("Nombre:");
        jLabel13.setAlignmentX(1.0F);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 170, 50, 14);

        nom.setAlignmentX(1.0F);
        getContentPane().add(nom);
        nom.setBounds(90, 160, 185, 30);

        jLabel14.setText("Email:");
        jLabel14.setAlignmentX(1.0F);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 210, 40, 14);

        mail.setAlignmentX(1.0F);
        getContentPane().add(mail);
        mail.setBounds(90, 200, 190, 30);

        jLabel15.setText("Gastado:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(460, 330, 60, 14);
        getContentPane().add(gastado);
        gastado.setBounds(520, 320, 110, 30);

        jLabel16.setText("Bonos:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(470, 370, 50, 14);
        getContentPane().add(bonos);
        bonos.setBounds(520, 360, 90, 30);

        jLabel17.setText("Estado:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(480, 420, 50, 14);
        getContentPane().add(estado);
        estado.setBounds(520, 410, 90, 40);

        jLabel18.setText("Provincia:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 470, 60, 14);
        getContentPane().add(provincia);
        provincia.setBounds(90, 460, 210, 40);

        jLabel19.setText("NIF:");
        jLabel19.setAlignmentX(1.0F);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 130, 30, 14);

        nif.setAlignmentX(1.0F);
        getContentPane().add(nif);
        nif.setBounds(90, 120, 100, 30);

        jLabel12.setText("Alquileres Foto del cliente | Carnet | Personas autorizadas | Observaciones |");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(770, 40, 420, 14);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/flecha-derecha.png"))); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/flecha-izquierda.png"))); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/doc.png"))); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/guardar.png"))); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/papelerareciclage.png"))); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/click.png"))); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/cancelar.png"))); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/buscar.png"))); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/salir.png"))); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Socis soc = new Socis();
        soc.setBackground(java.awt.Color.yellow);


    }//GEN-LAST:event_formWindowActivated

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        //botón derecha
        endevant++;
        int contadorLinias = 0;
        try {

            FileReader fw1 = new FileReader("datos.txt");
            BufferedReader br1 = new BufferedReader(fw1);
            while ((br1.readLine()) != null) {
                contadorLinias++;
            }
            br1.close();
            fw1.close();
        } catch (Exception e) {
            System.out.println("Error " + e);
        }

        if (endevant >= contadorLinias) {
            clientNum.setEnabled(true);
            nif.setEnabled(true);
            nom.setEnabled(true);
            mail.setEnabled(true);
            nacimiento.setEnabled(true);
            poblacion.setEnabled(true);
            postal.setEnabled(true);
            telf1.setEnabled(true);
            telf2.setEnabled(true);
            direccion.setEnabled(true);
            provincia.setEnabled(true);
            antiguedad.setEnabled(true);
            debe.setEnabled(true);
            alquilerUltimo.setEnabled(true);
            alquiler.setEnabled(true);
            credito.setEnabled(true);
            bonos.setEnabled(true);
            estado.setEnabled(true);
            gastado.setEnabled(true);
            clientNum.setText("");
            nif.setText("");
            nom.setText("");
            mail.setText("");
            nacimiento.setText("");
            poblacion.setText("");
            postal.setText("");
            telf1.setText("");
            telf2.setText("");
            direccion.setText("");
            provincia.setText("");
            antiguedad.setText("");
            debe.setText("");
            alquilerUltimo.setText("");
            alquiler.setText("");
            credito.setText("");
            bonos.setText("");
            estado.setText("");
            gastado.setText("");

        } else {
            try {
                String client = arraySocios.get(endevant);
                String[] clientInf = new String[arraySocios.size()];
                clientInf = arraySocios.get(endevant).split(",");
                clientNum.setText(clientInf[0]);
                nif.setText(clientInf[1]);
                nom.setText(clientInf[2]);
                mail.setText(clientInf[3]);
                nacimiento.setText(clientInf[4]);
                poblacion.setText(clientInf[5]);
                postal.setText(clientInf[6]);
                telf1.setText(clientInf[7]);
                telf2.setText(clientInf[8]);
                direccion.setText(clientInf[9]);
                provincia.setText(clientInf[10]);
                antiguedad.setText(clientInf[11]);
                debe.setText(clientInf[12]);
                alquilerUltimo.setText(clientInf[13]);
                alquiler.setText(clientInf[14]);
                credito.setText(clientInf[15]);
                bonos.setText(clientInf[16]);
                estado.setText(clientInf[17]);
                gastado.setText(clientInf[18]);

            } catch (Exception e) {
                System.out.println("Error de lectura de datos.txt al pasar derecha" + e);
            } // TODO add your handling code here:
        }

    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        //botón izquierda
        endevant--;
        try {
            String client = arraySocios.get(endevant);
            String[] clientInf = new String[arraySocios.size()];
            clientInf = arraySocios.get(endevant).split(",");
            clientNum.setText(clientInf[0]);
            nif.setText(clientInf[1]);
            nom.setText(clientInf[2]);
            mail.setText(clientInf[3]);
            nacimiento.setText(clientInf[4]);
            poblacion.setText(clientInf[5]);
            postal.setText(clientInf[6]);
            telf1.setText(clientInf[7]);
            telf2.setText(clientInf[8]);
            direccion.setText(clientInf[9]);
            provincia.setText(clientInf[10]);
            antiguedad.setText(clientInf[11]);
            debe.setText(clientInf[12]);
            alquilerUltimo.setText(clientInf[13]);
            alquiler.setText(clientInf[14]);
            credito.setText(clientInf[15]);
            bonos.setText(clientInf[16]);
            estado.setText(clientInf[17]);
            gastado.setText(clientInf[18]);
            clientNum.setEnabled(false);
            nif.setEnabled(false);
            nom.setEnabled(false);
            mail.setEnabled(false);
            nacimiento.setEnabled(false);
            poblacion.setEnabled(false);
            postal.setEnabled(false);
            telf1.setEnabled(false);
            telf2.setEnabled(false);
            direccion.setEnabled(false);
            provincia.setEnabled(false);
            antiguedad.setEnabled(false);
            debe.setEnabled(false);
            alquilerUltimo.setEnabled(false);
            alquiler.setEnabled(false);
            credito.setEnabled(false);
            bonos.setEnabled(false);
            estado.setEnabled(false);
            gastado.setEnabled(false);
            /*br.close();
             fw.close();*/
        } catch (Exception e) {
            System.out.println("Error de lectura de datos.txt" + e);
        } // TODO add your handling code here:      // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        //boton guardar 
        try {

            FileWriter fstream = new FileWriter("datos.txt", true);
            BufferedWriter out = new BufferedWriter(fstream);
            out.newLine();
            out.write(clientNum.getText() + "," + nif.getText() + "," + nom.getText() + "," + mail.getText() + "," + nacimiento.getText() + "," + poblacion.getText() + ","
                    + postal.getText() + "," + telf1.getText() + "," + telf2.getText() + "," + direccion.getText() + "," + provincia.getText() + "," + antiguedad.getText() + ","
                    + debe.getText() + "," + alquilerUltimo.getText() + "," + alquiler.getText() + "," + credito.getText() + "," + bonos.getText() + "," + estado.getText() + "," + gastado.getText());

            endevant = 0;
            out.close();
            fstream.close();
            String linia;
            try {
                arraySocios.clear();
                FileReader fw = new FileReader("datos.txt");
                BufferedReader br = new BufferedReader(fw);
                while ((linia = br.readLine()) != null) {
                    arraySocios.add(linia);
                }
                String client = arraySocios.get(0);
                String[] clientInf = new String[arraySocios.size()];
                clientInf = arraySocios.get(0).split(",");
                clientNum.setText(clientInf[0]);
                nif.setText(clientInf[1]);
                nom.setText(clientInf[2]);
                mail.setText(clientInf[3]);
                nacimiento.setText(clientInf[4]);
                poblacion.setText(clientInf[5]);
                postal.setText(clientInf[6]);
                telf1.setText(clientInf[7]);
                telf2.setText(clientInf[8]);
                direccion.setText(clientInf[9]);
                provincia.setText(clientInf[10]);
                antiguedad.setText(clientInf[11]);
                debe.setText(clientInf[12]);
                alquilerUltimo.setText(clientInf[13]);
                alquiler.setText(clientInf[14]);
                credito.setText(clientInf[15]);
                bonos.setText(clientInf[16]);
                estado.setText(clientInf[17]);
                gastado.setText(clientInf[18]);
                clientNum.setEnabled(false);
            nif.setEnabled(false);
            nom.setEnabled(false);
            mail.setEnabled(false);
            nacimiento.setEnabled(false);
            poblacion.setEnabled(false);
            postal.setEnabled(false);
            telf1.setEnabled(false);
            telf2.setEnabled(false);
            direccion.setEnabled(false);
            provincia.setEnabled(false);
            antiguedad.setEnabled(false);
            debe.setEnabled(false);
            alquilerUltimo.setEnabled(false);
            alquiler.setEnabled(false);
            credito.setEnabled(false);
            bonos.setEnabled(false);
            estado.setEnabled(false);
            gastado.setEnabled(false);
                br.close();
                fw.close();
            } catch (Exception e) {
                System.out.println("Error de lectura de datos.txt" + e);
            }

        } catch (Exception e) {
            System.out.println("Error " + e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        //error
        String linea;
        int lineaPas = 0;

        try {

            FileReader fw = new FileReader("datos.txt");
            BufferedReader br = new BufferedReader(fw);

            while ((linea = br.readLine()) != null) {
                if (lineaPas == endevant) {
                    arraySocios.remove(endevant);
                }
                lineaPas++;
            }
            fw.close();
            br.close();
            for (int i = 0; i < arraySocios.size(); i++) {
                System.out.println(arraySocios.get(i));
            }
            PrintWriter out = new PrintWriter("datos.txt");
            for (int i = 0; i < arraySocios.size(); i++) {
                out.write(arraySocios.get(i));
                out.println();
            }
            out.close();

        } catch (Exception e) {
            System.out.println("Error de eliminación" + e);
        }
        String client = arraySocios.get(0);
        String[] clientInf = new String[arraySocios.size()];
        clientInf = arraySocios.get(0).split(",");
        clientNum.setText(clientInf[0]);
        nif.setText(clientInf[1]);
        nom.setText(clientInf[2]);
        mail.setText(clientInf[3]);
        nacimiento.setText(clientInf[4]);
        poblacion.setText(clientInf[5]);
        postal.setText(clientInf[6]);
        telf1.setText(clientInf[7]);
        telf2.setText(clientInf[8]);
        direccion.setText(clientInf[9]);
        provincia.setText(clientInf[10]);
        antiguedad.setText(clientInf[11]);
        debe.setText(clientInf[12]);
        alquilerUltimo.setText(clientInf[13]);
        alquiler.setText(clientInf[14]);
        credito.setText(clientInf[15]);
        bonos.setText(clientInf[16]);
        estado.setText(clientInf[17]);
        gastado.setText(clientInf[18]);
        endevant = 0;

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        //Botón modificar
        clientNum.setEnabled(true);
        nif.setEnabled(true);
        nom.setEnabled(true);
        mail.setEnabled(true);
        nacimiento.setEnabled(true);
        poblacion.setEnabled(true);
        postal.setEnabled(true);
        telf1.setEnabled(true);
        telf2.setEnabled(true);
        direccion.setEnabled(true);
        provincia.setEnabled(true);
        antiguedad.setEnabled(true);
        debe.setEnabled(true);
        alquilerUltimo.setEnabled(true);
        alquiler.setEnabled(true);
        credito.setEnabled(true);
        bonos.setEnabled(true);
        estado.setEnabled(true);
        gastado.setEnabled(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        arraySocios.set(endevant, clientNum.getText() + "," + nif.getText() + "," + nom.getText() + "," + mail.getText() + "," + nacimiento.getText() + "," + poblacion.getText() + ","
                + postal.getText() + "," + telf1.getText() + "," + telf2.getText() + "," + direccion.getText() + "," + provincia.getText() + "," + antiguedad.getText() + ","
                + debe.getText() + "," + alquilerUltimo.getText() + "," + alquiler.getText() + "," + credito.getText() + "," + bonos.getText() + "," + estado.getText() + "," + gastado.getText());
        try {
            PrintWriter out = new PrintWriter("datos.txt");
            for (int i = 0; i < arraySocios.size(); i++) {
                out.write(arraySocios.get(i));
                out.println();
            }
            out.close();
        } catch (Exception e) {
            System.out.println("Error " + e);
        }
        String[] clientInf = new String[arraySocios.size()];
        clientInf = arraySocios.get(0).split(",");
        clientNum.setText(clientInf[0]);
        nif.setText(clientInf[1]);
        nom.setText(clientInf[2]);
        mail.setText(clientInf[3]);
        nacimiento.setText(clientInf[4]);
        poblacion.setText(clientInf[5]);
        postal.setText(clientInf[6]);
        telf1.setText(clientInf[7]);
        telf2.setText(clientInf[8]);
        direccion.setText(clientInf[9]);
        provincia.setText(clientInf[10]);
        antiguedad.setText(clientInf[11]);
        debe.setText(clientInf[12]);
        alquilerUltimo.setText(clientInf[13]);
        alquiler.setText(clientInf[14]);
        credito.setText(clientInf[15]);
        bonos.setText(clientInf[16]);
        estado.setText(clientInf[17]);
        gastado.setText(clientInf[18]);
        clientNum.setEnabled(false);
        nif.setEnabled(false);
        nom.setEnabled(false);
        mail.setEnabled(false);
        nacimiento.setEnabled(false);
        poblacion.setEnabled(false);
        postal.setEnabled(false);
        telf1.setEnabled(false);
        telf2.setEnabled(false);
        direccion.setEnabled(false);
        provincia.setEnabled(false);
        antiguedad.setEnabled(false);
        debe.setEnabled(false);
        alquilerUltimo.setEnabled(false);
        alquiler.setEnabled(false);
        credito.setEnabled(false);
        bonos.setEnabled(false);
        estado.setEnabled(false);
        gastado.setEnabled(false);

    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        String[] clientInf = new String[arraySocios.size()];
        clientInf = arraySocios.get(0).split(",");
        clientNum.setText(clientInf[0]);
        nif.setText(clientInf[1]);
        nom.setText(clientInf[2]);
        mail.setText(clientInf[3]);
        nacimiento.setText(clientInf[4]);
        poblacion.setText(clientInf[5]);
        postal.setText(clientInf[6]);
        telf1.setText(clientInf[7]);
        telf2.setText(clientInf[8]);
        direccion.setText(clientInf[9]);
        provincia.setText(clientInf[10]);
        antiguedad.setText(clientInf[11]);
        debe.setText(clientInf[12]);
        alquilerUltimo.setText(clientInf[13]);
        alquiler.setText(clientInf[14]);
        credito.setText(clientInf[15]);
        bonos.setText(clientInf[16]);
        estado.setText(clientInf[17]);
        gastado.setText(clientInf[18]);
        clientNum.setEnabled(false);
        nif.setEnabled(false);
        nom.setEnabled(false);
        mail.setEnabled(false);
        nacimiento.setEnabled(false);
        poblacion.setEnabled(false);
        postal.setEnabled(false);
        telf1.setEnabled(false);
        telf2.setEnabled(false);
        direccion.setEnabled(false);
        provincia.setEnabled(false);
        antiguedad.setEnabled(false);
        debe.setEnabled(false);
        alquilerUltimo.setEnabled(false);
        alquiler.setEnabled(false);
        credito.setEnabled(false);
        bonos.setEnabled(false);
        estado.setEnabled(false);
        gastado.setEnabled(false);
        endevant = 0;
    }//GEN-LAST:event_jMenu7MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String linia;
        try {
            FileReader fw = new FileReader("datos.txt");
            BufferedReader br = new BufferedReader(fw);
            while ((linia = br.readLine()) != null) {
                arraySocios.add(linia);
            }
            String client = arraySocios.get(0);
            String[] clientInf = new String[arraySocios.size()];
            clientInf = arraySocios.get(0).split(",");
            clientNum.setText(clientInf[0]);
            nif.setText(clientInf[1]);
            nom.setText(clientInf[2]);
            mail.setText(clientInf[3]);
            nacimiento.setText(clientInf[4]);
            poblacion.setText(clientInf[5]);
            postal.setText(clientInf[6]);
            telf1.setText(clientInf[7]);
            telf2.setText(clientInf[8]);
            direccion.setText(clientInf[9]);
            provincia.setText(clientInf[10]);
            antiguedad.setText(clientInf[11]);
            debe.setText(clientInf[12]);
            alquilerUltimo.setText(clientInf[13]);
            alquiler.setText(clientInf[14]);
            credito.setText(clientInf[15]);
            bonos.setText(clientInf[16]);
            estado.setText(clientInf[17]);
            gastado.setText(clientInf[18]);
            clientNum.setEnabled(false);
            nif.setEnabled(false);
            nom.setEnabled(false);
            mail.setEnabled(false);
            nacimiento.setEnabled(false);
            poblacion.setEnabled(false);
            postal.setEnabled(false);
            telf1.setEnabled(false);
            telf2.setEnabled(false);
            direccion.setEnabled(false);
            provincia.setEnabled(false);
            antiguedad.setEnabled(false);
            debe.setEnabled(false);
            alquilerUltimo.setEnabled(false);
            alquiler.setEnabled(false);
            credito.setEnabled(false);
            bonos.setEnabled(false);
            estado.setEnabled(false);
            gastado.setEnabled(false);
            br.close();
            fw.close();

        } catch (Exception e) {
            System.out.println("Error de lectura de datos.txt" + e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        int buscarClient = Integer.parseInt(JOptionPane.showInputDialog("Introduce el codigo del socio a buscar"));
        buscarClient--;
        String client = arraySocios.get(buscarClient);
        String[] clientInf = new String[arraySocios.size()];
        clientInf = arraySocios.get(buscarClient).split(",");
        clientNum.setText(clientInf[0]);
        nif.setText(clientInf[1]);
        nom.setText(clientInf[2]);
        mail.setText(clientInf[3]);
        nacimiento.setText(clientInf[4]);
        poblacion.setText(clientInf[5]);
        postal.setText(clientInf[6]);
        telf1.setText(clientInf[7]);
        telf2.setText(clientInf[8]);
        direccion.setText(clientInf[9]);
        provincia.setText(clientInf[10]);
        antiguedad.setText(clientInf[11]);
        debe.setText(clientInf[12]);
        alquilerUltimo.setText(clientInf[13]);
        alquiler.setText(clientInf[14]);
        credito.setText(clientInf[15]);
        bonos.setText(clientInf[16]);
        estado.setText(clientInf[17]);
        gastado.setText(clientInf[18]);
        endevant=buscarClient;
    }//GEN-LAST:event_jMenu8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Socis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Socis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Socis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Socis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Socis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alquiler;
    private javax.swing.JFormattedTextField alquilerUltimo;
    private javax.swing.JTextField antiguedad;
    private javax.swing.JTextField bonos;
    private javax.swing.JTextField clientNum;
    private javax.swing.JTextField credito;
    private javax.swing.JTextField debe;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField estado;
    private javax.swing.JTextField gastado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nacimiento;
    private javax.swing.JTextField nif;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField poblacion;
    private javax.swing.JTextField postal;
    private javax.swing.JTextField provincia;
    private javax.swing.JTextField telf1;
    private javax.swing.JTextField telf2;
    // End of variables declaration//GEN-END:variables
}
